export const EventStrings = {

  PANEL_SOAT_DIGITAL: '1',
  PANEL_SOAT_LASER: '2',
  PANEL_VER_GRAFICA: '3',

  LOGIN: '4',

  HOME_IR_SOAT: '5',
  HOME_IR_SCTR: '6',
  HOME_IR_VIDALEY: '7',
  HOME_IR_AP: '8',
  HOME_IR_SCTR2: '9',
  HOME_IR_OTROS: '10',

  SOAT_EMISION_BUSCARPLACA: '11',
  SOAT_EMISION_IRRESUMEN: '12',

  SOAT_RESUMEN_PE: '13',
  SOAT_RESUMEN_VISA: '14',
  SOAT_RESUMEN_CREDITO: '15',

  HISTORIAL_INGRESAR: '16',
  HISTORIAL_BUSCAR: '17',
  HISTORIAL_IMPRIMIRDIGITAL: '18',
  HISTORIAL_REENVIARDIGITAL: '19',
  HISTORIAL_FACTURAR: '20',
  HISTORIAL_DESCARGAREXCEL: '21',

  COMMLOT_INGRESAR: '22',
  COMMLOT_VERHISTORIAL: '23',
  COMMLOT_BUSCAR: '24',
  COMMLOT_CREAR: '25',
  COMMLOT_ACTUALIZAR: '26',

  PAYROLL_INGRESAR: '27',
  PAYROLL_VERHISTORIAL: '28',
  PAYROLL_BUSCAR: '29',
  PAYROLL_CREAR: '30',
  PAYROLL_ACTUALIZAR: '31',
  PAYROLL_EXPORTAR: '32',
  PAYROLL_ANULAR: '33',
  PAYROLL_CONCILIAR: '34',
  PAYROLL_DESCARGAR_DETALLE: '35',

  GESTORCREDITOS_INGRESAR: '36',
  GESTORCREDITOS_EXPORTAR: '37',
  GESTORCREDITOS_ACTUALIZAR: '38',

  BONOS_INGRESAR: '39',
  BONOS_DESCARGARPDF: '40',
  BONOS_VERDETALLE: '41',
  BONOS_DESCARGARDETALLE: '42',
  REPORTE_PRODUCCION: '43',
};

