export class CommissionAuth {
  constructor(
    public amount: number,
    public dauthorization: string,
    public dstartdate: string,
    public grouprows: number,
    public nbillnum: number,
    public sbillnum: string,
    public nbranch: number,
    public ncertif: number,
    public ncodchannel: number,
    public ncurrency: number,
    public ngrossup: number,
    public nidpayroll: number,
    public nidstatuS_COMMISSION: number,
    public nidstatus: number,
    public npage: number,
    public npercent: number,
    public spercent: string,
    public npolicy: number,
    public npremium: number,
    public nproduct: number,
    public nreceipt: number,
    public nrecorD_COUNT: number,
    public nrecordpage: number,
    public nstatecommiss: number,
    public rownumber: number,
    public sbilltype: string,
    public sbranch: string,
    public scertype: string,
    public scodchannel: string,
    public scurrency: string,
    public selected: boolean,
    public sname: string,
    public sproduct: string,
    public sregist: string,
    public sshorT_CURRENCY: string,
    public sstatecommiss: string,
    public sstatuS_COMMISSION: string,
    public sstatuS_POL_DES: string,
    public niduser: number,
    public comprobante: string,
    public stype: number
  ) {}
}
export class CommissionAuthModel {
  constructor(
    public agrupado: boolean,
    public canal: string,
    public cantidadRegistros: number,
    public codigoCanal: number,
    public comprobante: string,
    public fechaDisponibilizacion: string,
    public fechaFacturacion: string,
    public idJob: number,
    public idMoneda: number,
    public idProducto: number,
    public idRamo: number,
    public indice: number,
    public moneda: string,
    public montoComision: number,
    public numeroPoliza: number,
    public numeroReciboFin: number,
    public numeroReciboInicio: number,
    public numeroRecibo: number,
    public porcentajeComision: number,
    public primaNeta: number,
    public primaTotal: number,
    public producto: string,
    public selected: boolean,
    public identificador: number,
    public checked: boolean,
    public disabled: boolean
  ) {}
}
