 // Lista de endpoints que requieren encriptación
 export const ENCRYPTED_ENDPOINTS: string[] = [
//     'Api/Maintenance/getProfileProduct',
//     'Api/ProspectsManager/GetAsesorVIGP',
//     'Api/ProspectsManager/GetAllProspect',
//     'Api/SharedManager/GetCivilStatusList',
//     'Api/SharedManager/GetGenderList',
//     'Api/ProspectsManager/ValidateClientProspect',
//     'Api/CalidadDatos/gestionarDatos',
//     'Api/ProspectsManager/ConsultProspect',
//     'Api/ProspectsManager/ConsultaIdecom',
//     'Api/ProspectsManager/InsertProspect',
//     'Api/ProspectsManager/SaveDirection',
//     'Api/SharedManager/GetCurrencyList',
//     'Api/QuotationManager/SavingTime',
//     'Api/QuotationManager/GetListaPlanes',
//     'Api/ProspectsManager/GetProspectById',
//     'Api/ProspectsManager/ConsultaWorldCheck',
//     'Api/ProspectsManager/InsUpdWorldCheck',
//     'Api/ClientManager/InvokeServiceExperia',
//     'Api/ProspectsManager/ConsultDataComplementary',
//     'Api/QuotationManager/GetCotizacionesVigentesVIGP',
//     'Api/QuotationManager/GetScoringOptions',
//     'Api/QuotationManager/ValidateFundDate',
//     'Api/QuotationManager/GetFechaFinVigenciaPoliza',
//     'Api/QuotationManager/UpdDataComplementaryVIGP',
//     'Api/QuotationManager/InsertQuotation',
//     'Api/ProspectsManager/InsUpdQOPep',
//     'Api/QuotationManager/RequestScoring',
//     'Api/QuotationManager/GetCotizacionesNoVigentesVIGP',
//     'Api/QuotationManager/InsPerfilamiento',
//     'Api/SharedManager/DonwloadSLipVIGP',
//     'Api/PDFGenerator/SendDocument',
//     'Api/QuotationManager/GetQuotationsVIGP',
//     'Api/QuotationManager/ReadDocumentsVIGP',
//     'Api/QuotationManager/GetCommentsCotiVIGP',
//     'Api/QuotationManager/SelDatosPEPVIGP',
//     'Api/QuotationManager/InvestmentFunds',
//     'Api/QuotationManager/GetCotizacionPre',
//     'Api/QuotationManager/GetOriginDetailCab',
//     'Api/SharedManager/GetCodesList',
//     'Api/QuotationManager/GetDatosPepFam',
//     'Api/QuotationManager/getRelationsPep',
//     'Api/QuotationManager/PostFamily',
//     'Api/QuotationManager/GetDatosPepRelatives',
//     'Api/SharedManager/GetNationalityList',
//     'Api/QuotationManager/PostRelative',
//     'Api/QuotationManager/InsUpdDatosPEPVIGP',
//     'Api/QuotationManager/GetDatosWork',
//     'Api/QuotationManager/PostWorks',
//     'Api/QuotationManager/GetNidStateCotizac',
//     'Api/QuotationManager/GetRoutesDocsPep',
//     'Api/SharedManager/DownloadFile',
//     'Api/QuotationManager/InsCommentsCotiVIGP',
//     'Api/QuotationManager/ChangeInsuredPd',
//     'Api/QuotationManager/GetProviderListVIGP',
//     'Api/QuotationManager/InsUpdOriginDetailCab',
//     'Api/QuotationManager/InsUpdOriginDetailDet',
//     'Api/QuotationManager/DownloadDocumentsVIGP',
//     'Api/QuotationManager/InsUpdCotiStatesVIGP',
//     'Api/QuotationManager/InsUpdCotiStatesVIGPDoc',
//     'Api/QuotationManager/GetDatosPep',
//     'Api/CalidadDatos/gestionarDatosIns',
//     'Api/QuotationManager/CleanBeneficiar',
//     'Api/ProspectsManager/GetSupervisorVIGP',
//     'Api/QuotationManager/Scoring',
//     'Api/ProspectsManager/ConsultaOriginPep',
//     'Api/ProspectsManager/ConsultDataComplementary',
//     'Api/QuotationManager/GetNidStateAndDefState',
//     'Api/ProspectsManager/GetJefe',
//     'Api/QuotationManager/SaveDocumentsVIGP',
//     'Api/QuotationManager/UpdateSignatureType',
//     'Api/QuotationManager/InsFirmaElectronicaVIGP',
//     'Api/QuotationManager/UpdateHandwrittenStatus',
//     'Api/QuotationManager/ValidarListoParaEmitir',
//     'Api/QuotationManager/GetAdditionalInformationPolicy',
//     'Api/SharedManager/GetDepartmentList',
//     'Api/SharedManager/GetDistrictList',
//     'Api/SharedManager/GetDocumentTypeList',
//     'Api/QuotationManager/GetExpirDate',
//     'Api/QuotationManager/GetFileClientStates',
//     'Api/QuotationManager/GetHistorialEvaluaciones',
//     'Api/SharedManager/GetOccupationTypeList',
//     'Api/QuotationManager/GetOriginDetailDet',
//     'Api/SharedManager/GetProvinceList',
//     'Api/QuotationManager/GetQuotationDefinitiveConsult',
//     'Api/QuotationManager/GetRelationBenefeciaries',
//     'Api/QuotationManager/GetStatusList',
//     'Api/ProspectsManager/InsUpdIdecom',
//     'Api/PolicyManager/PolizaEmitCab',
//     'Api/ProspectsManager/SearchProspectQuotation',
//     'Api/ClientManager/SourceXClient',
//     'Api/PolicyManager/InsPreTransac',
   //Inmobiliaria
  'Api/InmoClosingDateConfig/ListarConfiguraciones',
  'Api/InmoClosingDateConfig/AgregarConfiguracion',
  'Api/InmoClosingDateConfig/ModificarConfiguracion',
  'Api/InmoClosingDateConfig/EliminarConfiguracion',
  'Api/InmoClosingDateConfig/ListarEstados',
  'Api/InmoClosingDateConfig/ListarRamos',
  'Api/InmoClosingDateConfig/ListarMeses',
  'Api/InmoInterfaceDependence/ListarDependenciasInterfaces',
  'Api/InmoInterfaceDependence/AgregarDependenciasInterfaces',
  'Api/InmoInterfaceDependence/EliminarDependenciasInterfaces',
  'Api/InmoInterfaceDependence/ListarPrioridadesInterfaces',
  'Api/InmoInterfaceDependence/EliminarAgregarPrioridadesInterfaces',
  'Api/InmoInterfaceDependence/ListarDependenciasInterfacesFiltradas',
  'Api/InmoInterfaceMonitoringCBCO/ListarEstados',
  'Api/InmoInterfaceMonitoringCBCO/ListarCabeceraInterfacesCBCO',
  'Api/InmoInterfaceMonitoringCBCO/ListarCabeceraInterfacesCBCORecibo',
  'Api/InmoInterfaceMonitoringCBCO/ListarDetalleInterfacesCBCO',
  'Api/InmoInterfaceMonitoringCBCO/ListarDetalleOperacion',
  'Api/InmoInterfaceMonitoringCBCO/ListarDetalleInterfacesXLSX_CBCO',
  'Api/InmoInterfaceMonitoringCBCO/ListarDetalleInterfacesAsientosContables',
  'Api/InmoInterfaceMonitoringCBCO/ListarDetalleInterfacesAsientosContablesAsiento',
  'Api/InmoInterfaceMonitoringCBCO/ListarDetalleInterfacesAsientosContablesError',
  'Api/InmoInterfaceMonitoringCBCO/ListarDetalleInterfacesExactus',
  'Api/InmoInterfaceMonitoringCBCO/ListarDetalleInterfacesExactusAsiento',
  'Api/InmoInterfaceMonitoringCBCO/ListarDetalleInterfacesExactusError',
  'Api/InmoInterfaceMonitoringCBCO/ListarDetalleInterfacesAsientosContablesOP',
  'Api/InmoInterfaceMonitoringCBCO/ListarDetalleInterfacesAsientosContablesAsientoOP',
  'Api/InmoInterfaceMonitoringCBCO/ListarDetalleInterfacesExactusOP',
  'Api/InmoInterfaceMonitoringCBCO/ListarDetalleInterfacesExactusAsientoOP',
  'Api/InmoInterfaceMonitoring/ListarEstados',
  'Api/InmoInterfaceMonitoring/ListarCabeceraInterfaces',
  'Api/InmoInterfaceMonitoring/ListarCabeceraInterfacesRecibo',
  'Api/InmoInterfaceMonitoring/ListarDetalleInterfaces',
  'Api/InmoInterfaceMonitoring/ListarErroresDetalle',
  'Api/InmoInterfaceMonitoring/ListarDetalleInterfacesAsientosContables',
  'Api/InmoInterfaceMonitoring/ListarDetalleInterfacesAsientosContablesAsiento',
  'Api/InmoInterfaceMonitoring/ListarDetalleInterfacesAsientosContablesError',
  'Api/InmoInterfaceMonitoring/ListarDetalleInterfacesExactus',
  'Api/InmoInterfaceMonitoring/ListarDetalleInterfacesExactusAsiento',
  'Api/InmoInterfaceMonitoring/ListarDetalleInterfacesExactusError',
  'Api/InmoInterfaceMonitoring/ListarTipoBusqueda',
  'Api/InmoInterfaceMonitoring/ListarTipoBusquedaSI',
  'Api/InmoInterfaceMonitoring/ListarDetalleOperacion',
  'Api/InmoInterfaceMonitoring/ListarDetalleInterfacesXLSX',
  'Api/InmoInterfaceMonitoring/ListarDetalleInterfacesXLSX_CB',
  'Api/InmoInterfaz/ListarOrigen',
  'Api/InmoInterfaz/ListarEstados',
  'Api/InmoInterfaz/ListarTipoAsiento',
  'Api/InmoInterfaz/ConsultarTipoAsiento',
  'Api/InmoInterfaz/ListarReportesAsociados',
  'Api/InmoInterfaz/ListarInterfaz',
  'Api/InmoInterfaz/AgregarInterfaz',
  'Api/InmoInterfaz/ModificarInterfaz',
  'Api/InmoInterfaz/EliminarInterfaz',
  'Api/InmoInterfaz/ListarMovimientos',
  'Api/InmoInterfaz/AgregarMovimientos',
  'Api/InmoInterfaz/ModificarMovimientos',
  'Api/InmoInterfaz/EliminarMovimientos',
  'Api/InmoModuleReports/ProcessReportContable',
  'Api/InmoModuleReports/ProcessReportOperaciones',
  'Api/InmoModuleReports/ProcessReportControlBancario',
  'Api/InmoModuleReports/ProcessReportCuentasPorCobrar',
  'Api/InmoReprocess/InsertarReproceso',
  'Api/InmoReprocess/InsertarReprocesoAsi',
  'Api/InmoReprocess/InsertarReprocesoAsi_CBCO',
  'Api/LoadMassiveIM/GetBranchList',
  'Api/LoadMassiveIM/ProcessHeaderList',
  'Api/LoadMassiveIM/ProcessDetailList',
  'Api/LoadMassiveIM/GetConfigurationPath',
  'Api/LoadMassiveIM/GetConfigurationEntity',
  'Api/LoadMassiveIM/GetConfigurationFiles',
  'Api/LoadMassiveIM/GetProductsList',
  'Api/LoadMassiveIM/UploadFileProcess',
  //'Api/LoadMassiveIM/ProcessFiles',
  'Api/LoadMassiveIM/GetDataExport',
  'Api/LoadMassiveIM/GetDataExportCorrect',
  'Api/LoadMassiveIM/GetProcessLogError',
  'Api/MaintenanceInmobiliary/GetTypeDocumentsList',
  'Api/MaintenanceInmobiliary/GetOptionList',
  'Api/MaintenanceInmobiliary/GetListBuscarPor',
  'Api/MaintenanceInmobiliary/GetListTipFacturacion',
  'Api/MaintenanceInmobiliary/GetContratantesList',
  'Api/MaintenanceInmobiliary/GetConsultaClientesList',
  'Api/MaintenanceInmobiliary/ListarDocumentosCierre',
  'Api/MaintenanceInmobiliary/ListarPorVencerCierre',
  'Api/MaintenanceInmobiliary/ListarEstadosBillsCierre',
  'Api/MaintenanceInmobiliary/GetInmobiliairyCierreReport',
  'Api/MaintenanceInmobiliary/GetDataReportInmobiliariasControlSeguimiento',
  'Api/MaintenanceInmobiliary/ListarTipoServicioCierre',
  'Api/MaintenanceInmobiliary/GetInmobiliairyReporteCierre',
  'Api/MaintenanceInmobiliary/GetDataInmobiliairyReporteCierre',
  'Api/MaintenanceInmobiliary/ListarGeneroInmobiliaria',
  'Api/MaintenanceInmobiliary/ListarNacionalidadInmobiliaria',
  'Api/MaintenanceInmobiliary/ListarEstadoCivilInmobiliaria',
  'Api/MaintenanceInmobiliary/ListarTipoDocumentoInmobiliaria',
  'Api/MaintenanceInmobiliary/GetClientDetInmobiliaria',
  'Api/MaintenanceInmobiliary/GetTipoVias',
  'Api/MaintenanceInmobiliary/GetDepartamentos',
  'Api/MaintenanceInmobiliary/GetProvincias',
  'Api/MaintenanceInmobiliary/GetDistrito',
  'Api/MaintenanceInmobiliary/GetDetalleDireccion',
  'Api/MaintenanceInmobiliary/GetExistsBills',
  'Api/MaintenanceInmobiliary/InsertarClienteInmobiliaria',
  'Api/MaintenanceInmobiliary/ActualizarClienteInmobiliaria',
  'Api/MaintenanceInmobiliary/PayDateInmob',
  'Api/MaintenanceInmobiliary/UpdCurrency'
 ];